---
title: "Presentations"
author: "Mireia Valle"
date: "14/02/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading required library
```{r}
# install.packages("dplyr")
library(dplyr)
```

# Set the random seed to make this reproducible

```{r}
set.seed(1)
```

# Create the participants data frame
```{r}
pp <- data.frame(
      numb = 1:11,
      names = c("Mathieu Pruvot",
              "Whitney Friedman",
              "April Ridlon",
              "Michael Eggen",
              "Jeremy Simmonds",
              "Jihoon Jung",
              "Dan Sousa",
              "Mireia Valle",
              "Grace Wu",
              "Marcus Thomson",
              "Hannah Fazekas"),
      stringsAsFactors = FALSE
)
```

# Random sampling

```{r}
pps <- sample_n(pp, nrow(pp))
```

# Assign the day

```{r}
ppf <-pps %>% mutate(pres_day = ifelse(row_number() %in% 1:6, "TUE", "WED"))
```

# Look at the results

```{r}
ppf
```
